### ISSUE TITLE
{"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by smitterer** [dkarv/hacs-lg-ess#1]
Thanks a lot for this integration!

When trying to set it up via "Integrations", I get {"message":"Invalid handler specified"}.
Using a ESS Home 5 Inverter.

Is it possible to manually define the local IP address?

Thank

**Comment by dkarv** [comment]
Hi, sorry for your issues. To debug them I would need more information, e.g. when you enable the debug protocol (red area in screenshot) and send me the logs.
Yes, you can add a device manually by using the blue "Add entry" button:
![image](https://github.com/dkarv/hacs-lg-ess/assets/3708591/40fa14ba-01f0-4014-afb3-caae26bfedef)

You can put in your ip address and password manually.

**Comment by smitterer** [comment]
Found out that this is not working with the V1 of LG Inverters due to a different SW. Had to switch over to https://github.com/e-sailing/LG-ESS-Gen1/tree/master/mqtt (which is working like a charme when it comes to reading the values out)
