### ISSUE TITLE
Repository dkarv/hacs-lg-ess not found

### ISSUE THREAD

**Issue by metalux2030** [dkarv/hacs-lg-ess#2]
Hi,
wondering if your repository is still live. I cannot find it in HACS.
Would love to use it to read all my data from the LG System.

Best
Jens

**Comment by dkarv** [comment]
Hi,

yes it is still live and working.
You need to add the repository url as custom repository in HACS (under the three dots in the top right).

**Comment by metalux2030** [comment]
Ah my fault. Thanks, it works now.
